### ISSUE TITLE
expr blocks in unused configs are parsed and evaluated

### ISSUE THREAD

**Issue by scottmmjackson** [jjallaire/config#20]
Reproduction steps:

1. Create a new rmarkdown document or shiny application containing the following:
```r
library(config)
c <- config::get()
cat(paste(c$foo, config::is_active('irrelevant')))
```
2. Create a new `config.yml` file in the content's folder:
```yaml
default:
    foo: bar

development:
    foo: development

irrelevant:
    foo: !expr BRRR::skrrrahh(sound = 26)
```
3. Run the content

#### Expected:

Standard output contains "bar", or "development" if `R_CONFIG_ACTIVE` is set to `development`, followed by FALSE.

#### Actual:

`Error in loadNamespace(name) : there is no package called ‘BRRR’`

-------

4. Now install https://github.com/brooke-watson/BRRR using `devtools::install_github('brooke-watson/BRRR')`

5. Run the content

#### Expected:

quiet

#### Actual:

Gucci Mane is played through the speakers irrespective of `R_CONFIG_ACTIVE`'s value.

"bar" or "development" is printed, followed by "FALSE", proving that `irrelevant` is not the config selected.
