### ISSUE TITLE
Feature Request: Add `default' argument to `get` to provide a fallback value

### ISSUE THREAD

**Issue by warnes** [jjallaire/config#28]
It would be helpful if `config::get` had a `default` argument to provide a value if none is found in `config.yml` (or if that file does not exist.)

For instance. Current code
```
db_user <- config::get("db_user")
if(is.null("db_user")) db_user <- "dbadmin"
```
desired code:
```
db_user <- config::get("db_user", default="dbadmin")
```

**Comment by andrie** [comment]
The existing mechanism already provides a mechanism for setting a default, but you have to do this in the `yaml`, rather in the `config::get()`:

```yaml
default:
  trials: 5
  dataset: "data-sampled.csv"
  
production:
  trials: 30
  dataset: "data.csv"
```

If you're concerned about catching missing values, then I suggest it's probably safer to write your own wrapper function or explicit error catching mechanism.
