### ISSUE TITLE
config::get to get values from nested yaml structures

### ISSUE THREAD

**Issue by berkorbay** [jjallaire/config#34]
As far as I could understand `config::get` can provide a list from the first level (e.g. `config::get("valgroup1")`) but it cannot provide values from the second level (e.g. `config::get("valgroup1:val1")`).

```yaml
default:
  valgroup1:
    val1: "value 1 of group 1"
    val2: "value 2 of group 1"
  valgroup2:
    val1: "value 1 of group 2"
    val2: "value 2 of group 2"
```

This is something that is nice to have but not essential.
