### ISSUE TITLE
No overwrite for object list

### ISSUE THREAD

**Issue by Rafnuss** [jjallaire/config#52]
Just trying to understand what I'm doing wrong with this config file

```yml
default:
  val: 1
  tag_set_map:
    - stap_id: [3, -1]

22NO:
  val: 2
  tag_set_map:
    - stap_id: 3
```

This makes sense to me:
```r
config::get(config = "22NO")$val
#> 2
```

But not this: 
```r
config::get(config = "22NO")$tag_set_map
#> [[1]]
#> [[1]]$stap_id
#> [1]  3 -1
```

How come 22NO is not overwriting the default for object list items? Or did I do something wrong?
Thanks,
